export { default as Contact } from './contact/Contact';
export { default as Intro } from './intro/Intro';
export { default as Menu } from './menu/Menu';
export { default as MenuItem } from './menuItem/MenuItem';
export { default as Portfolio } from './portfolio/Portfolio';
export { default as PortfolioList } from './portfolioList/PortfolioList';
export { default as Testimonials } from './testimonials/Testimonials';
export { default as Topbar } from './topbar/Topbar';
export { default as Works } from './works/Works';